### ISSUE TITLE
Creating EC2 routes fail due to already existing when deploying.

### ISSUE THREAD

**Issue by MarcelSpaceform** [aws-samples/nvidia-omniverse-nucleus-on-amazon-ec2#16]
Environment: Deploying using version v2023.1.0 of this repo in Visual Studio Code console using WSL ubuntu

- I am under the impression that the deploy process is making concurrent requests to create the same or similar routes which is causing the deploy to fail. 
- Perhaps too many route tables are being created as appose to one with multiple routes.

Here is the error on the console.

```
omni-app-nucleus-dev: deploying... [1/1]
omni-app-nucleus-dev: creating CloudFormation changeset...
11:35:59 AM | CREATE_FAILED        | AWS::EC2::Route                           | VpcResourcesOmniVp...faultRouteB86AFBA2
Resource handler returned message: "AlreadyExists" (RequestToken: 080ab3df-22a7-5b69-db67-1cecf711a294, HandlerErrorCode: AlreadyExists)

11:35:59 AM | CREATE_FAILED        | AWS::EC2::Route                           | VpcResourcesOmniVp...faultRouteA291E5F8
Resource handler returned message: "AlreadyExists" (RequestToken: 269005d6-5bb1-ed5b-0e80-20e66be29dac, HandlerErrorCode: AlreadyExists)
Resource handler returned message: "AlreadyExists" (RequestToken: 269005d6-5bb1-ed5b-0e80-20e66be29dac, HandlerErrorCode: AlreadyExists)

Resource handler returned message: "AlreadyExists" (RequestToken: 269005d6-5bb1-ed5b-0e80-20e66be29dac, HandlerErrorCode: AlreadyExists)

11:35:59 AM | CREATE_FAILED        | AWS::EC2::Route                           | VpcResourcesOmniVp...faultRoute118D220B
Resource handler returned message: "AlreadyExists" (RequestToken: 8fd72df0-6e87-020a-5d61-52a01412c72e, HandlerErrorCode: AlreadyExists)
```

**Comment by kellan-cartledge** [comment]
Thank you for informing us about this @MarcelSpaceform. I'll update once I'm able to reproduce this error. Please, feel free to share any additional information.

**Comment by MarcelSpaceform** [comment]
> Thank you for informing us about this @MarcelSpaceform. I'll update once I'm able to reproduce this error. Please, feel free to share any additional information.

@kellan-cartledge Thank you for your reply and efforts in trying to replicate my issue. Is there any specific info that you need from me to help out?

I can run the deploy again and take a screenshot of all the route tables that are created before they are rolled back and deleted. Would that help?

**Comment by kellan-cartledge** [comment]
Hey, @MarcelSpaceform, would it be possible to provide a step-by-step description of your deployment process? 

As well, are you upgrading to v2023.1.0 from the previous version of this project? If this is the case you'll need to remove the previous version prior to deploying v2023.1.0.

**Comment by MarcelSpaceform** [comment]
Hi @kellan-cartledge I have tried to deploy the app on 2 different environments, and I get that same issue as mentioned in the issue I submitted above.

The first environment was running the deploy script using Windows Subsystem for Linux (WSL) and a console connected to it from Visual Studio code application.

The second environment was a ubuntu 22 running in a virtual machine and setup with all the Prerequisites as mentioned in the read me.

Both setups were run after a public hosted zone was created for my domain in route53 and the ALLOWED_CIDR_RANGE_01 is being set to: 0.0.0.0/0

I hope you can assist as I really need to get the app up and running.

**Comment by kellan-cartledge** [comment]
Based on the descriptions of your local environments, the setup of these should be good. My assumption is there are existing Elastic Network Interfaces (ENIs), Network Access Control Lists (NACLs), or Route Tables in the destination AWS account that conflict with what is being configured by this project. 

If you are able to navigate to the CloudFormation service in the AWS web console, there should be a more detailed error description under the Stack/Events option -- you may have to scroll for awhile to get past the rolled back resources. If you are able to access this is it possible to share the details on this error from CloudFormation?

As well, please verify any unused resources are removed from the AWS account and Region you are deploying to. Or, are you able to test deploy to a clean/sandbox AWS account that has no resources in it?

**Comment by MarcelSpaceform** [comment]
@kellan-cartledge Thanks for your reply above. Your assumption was correct. The issue was conflicts with existing routes in the route tables for the CIDR range.

To get it working I just used my exact IP address of my machine in the meantime.

Thanks for your help

**Comment by kellan-cartledge** [comment]
Glad you hear you got it working @MarcelSpaceform. For now, I'm going to close this ticket.
